name: Build polyfill-glibc

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc ninja-build patchelf

    - name: Build polyfill-glibc and run it on itself
      shell: sh
      run: |
        ninja polyfill-glibc
        set -ex
        TOOL=$(find . -type f -name polyfill-glibc)
        strip "$TOOL"
        ls -lh "$TOOL"
        file "$TOOL"
        mkdir -p out/
        cp "$TOOL" out/
        "$TOOL" --target-glibc=2.17 out/*
        # Fix "Program headers not in the first page" on FreeBSD Linuxulator
        # https://github.com/AppImageCrafters/appimage-builder/issues/38#issuecomment-2681621404
        patchelf --set-interpreter $(patchelf --print-interpreter out/polyfill-glibc) out/polyfill-glibc
        ls -lh out/*
        file out/*

    - name: Upload files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        set -e
        wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
        bash upload.sh out/*
