name: Build polyfill-glibc

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: sh
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc ninja-build

    - name: Build polyfill-glibc
      shell: sh
      run: |
        ninja polyfill-glibc
